[package]
name = "rinha-de-backend-2026-fabio-rust"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
axum = { version = "0.6.20", default-features = false, features = ["http1", "json", "matched-path", "tokio"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4.31", default-features = false, features = ["clock", "std"] }
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread", "signal", "net", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
thiserror = "1"
memmap2 = "0.9"
bytemuck = { version = "1", features = ["derive"] }
clap = { version = "4.4.18", features = ["derive"] }
flate2 = "1"

[dev-dependencies]
hyper = { version = "0.14", features = ["client", "http1", "tcp"] }
tower = { version = "0.4.13", features = ["util"] }
